geekshop/admins/urls.py
from django.urls import path

from admins.views import index, UserListView, UserUpdateView, UserDeleteView, UserCreateView
from admins.views import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views import ProductListView,ProductCreateView,ProductUpdateView,ProductDeleteView

app_name = 'admins'
urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_users_delete'),

    path('categories/', CategoryListView.as_view(), name='admin_categories'),
    path('categories_create/', CategoryCreateView.as_view(), name='admin_categories_create'),
    path('categories_update/<int:pk>/', CategoryUpdateView.as_view(), name='admin_categories_update'),
    path('categories_delete/<int:pk>/', CategoryDeleteView.as_view(), name='admin_categories_delete'),

    path('products/', ProductListView.as_view(), name='admin_products'),
    path('products_create/', ProductCreateView.as_view(), name='admin_products_create'),
    path('products_update/<int:pk>/', ProductUpdateView.as_view(), name='admin_products_update'),
    path('products_delete/<int:pk>/', ProductDeleteView.as_view(), name='admin_products_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

#import authapp.views as authapp
from authapp.views import LoginListView, ProfileFormView, Logout, RegisterlistView

app_name = 'authapp'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('registration/', RegisterlistView.as_view(), name='registration'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name = 'logout'),


    path('verify/<str:email>/<str:activate_key>/', RegisterlistView.verify, name='verify')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index,products

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/admins/templates/admins/admin-categories-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание категории</h1>
                <form action="{% url 'admins:admin_categories_create' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>

                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-categories-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Активная</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for category in object_list %}
                                <tr style="{% if not category.is_active %} background-color: grey {% endif %}">
                                    <td><a href="{% url 'admins:admin_categories_update' category.pk %}" style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>{{ category.description}}</td>
                                    <td class="text-center">
                                        {% if category.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                                </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_categories_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-categories-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование категории | {{ productcategory.name}}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_categories_update' productcategory.pk %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>

                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_categories_delete' productcategory.pk %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; GeekShop 2021</div>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание продукта</h1>
                <form action="{% url 'admins:admin_products_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.short_desc.id_for_label }}">Краткое описание</label>
                            {{ form.short_desc }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена, руб.</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество, шт.</label>
                            {{ form.quantity }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Продукты</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукты
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Категория</th>
                                    <th>Картинка</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for product in object_list %}
                                <tr style="{% if not product.is_active %} background-color: grey {% endif %}">
                                    <td><a href="{% url 'admins:admin_products_update' product.id %}" style="color: dodgerblue">{{ product.name }}</a></td>
                                    <td>{{ product.category.name }}</td>
                                    <td><img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.short_desc }}"></td>
                                    <td>{{ product.description }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>

                                    <td class="text-center">
                                        {% if product.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                                </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_products_create' %}">
                            <button class="btn btn-success">Создать товар</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование товара | {{ product.username}}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_products_update' product.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.short_desc.id_for_label }}">Краткое описанме</label>
                            {{ form.short_desc }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена, руб.</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество, шт.</label>
                            {{ form.quantity }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_products_delete' product.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; GeekShop 2021</div>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание пользователя</h1>
                <form action="{% url 'admins:admin_users_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for user in object_list %}
                                <tr style="{% if not user.is_active %} background-color: grey {% endif %}">
                                    <td><a href="{% url 'admins:admin_users_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name}}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if user.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                                </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование пользователя | {{ user.username}}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; GeekShop 2021</div>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

geekshop/admins/templates/admins/admin.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}